// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegfyInsurance.Infrastructure.Data;

#nullable disable

namespace SegfyInsurance.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SegfyInsuranceDbContext))]
    partial class SegfyInsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("SegfyInsurance.Domain.Entities.ApoliceSeguro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndDate");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartDate");

                    b.Property<string>("DocumentoSegurado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InsuredDocument");

                    b.Property<string>("NumeroApolice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PolicyNumber");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("VehiclePlate");

                    b.Property<decimal>("PremioMensal")
                        .HasColumnType("REAL")
                        .HasColumnName("MonthlyPremium");

                    b.Property<int>("Situacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("NumeroApolice")
                        .IsUnique();

                    b.ToTable("InsurancePolicies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
